export const GET_ALL_COUNTRIES_LOADING = "GET_ALL_COUNTRIES_LOADING";
export const GET_ALL_COUNTRIES_SUCCESS = "GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_FAIL = "GET_ALL_COUNTRIES_FAIL";

export const GET_ALL_LEAGUES_LOADING = "GET_ALL_LEAGUES_LOADING";
export const GET_ALL_LEAGUES_SUCCESS = "GET_ALL_LEAGUES_SUCCESS";
export const GET_ALL_LEAGUES_FAIL = "GET_ALL_LEAGUES_FAIL";

export const GET_LEAGUE_LOADING = "GET_LEAGUE_LOADING";
export const GET_LEAGUE_SUCCESS = "GET_LEAGUE_SUCCESS";
export const GET_LEAGUE_FAIL = "GET_LEAGUE_FAIL";

export const GET_TEAM_LOADING = "GET_TEAM_LOADING";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_FAIL = "GET_TEAM_FAIL";

export const GET_TABLELOOKUP_LOADING = "GET_TABLELOOKUP_LOADING";
export const GET_TABLELOOKUP_SUCCESS = "GET_TABLELOOKUP_SUCCESS";
export const GET_TABLELOOKUP_FAIL = "GET_TABLELOOKUP_FAIL";